FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    ffmpeg \
    libgl1 \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender1 \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir --timeout 300 \
    fastapi==0.111.0 \
    uvicorn==0.30.0 \
    python-multipart==0.0.9 \
    tensorflow==2.17.0 \
    mediapipe==0.10.14 \
    opencv-python==4.10.0.84 \
    protobuf==4.25.3 \
    numpy==1.26.4

COPY sign_server.py .
COPY sign_to_class.pkl .
COPY model/ ./model/

EXPOSE 5001

CMD ["uvicorn", "sign_server:app", "--host", "0.0.0.0", "--port", "5001"]